apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--mtpy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--mtpy
    app.kubernetes.io/part-of: test-app-knri
  name: test-component--mtpy
  namespace: e2e-test-pipelines-cnnl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component--mtpy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component--mtpy
    spec:
      containers:
      - image: quay.io/codewindbtle/test-images:4b17efe78e234b68937de2bdb2aeb28d
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
